version: "3.7"

services:
  roundcube:
    container_name: roundcube
    image: roundcube/roundcubemail:latest
    restart: unless-stopped
    volumes:
      - ./data/www:/var/www/html
      - ./data/db/sqlite:/var/roundcube/db
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.nymann.dev
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.nymann.dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roundcube.rule=Host(`mail.nymann.dev`)"
      - "traefik.http.services.roundcube.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true
